-- Piel Dorada — Lista VIP waitlist with referral engine
-- Positions start at 248 (247 pre-launch baseline, first public signup is #248).
-- Referral counts are derived from referred_by rows — no counter column to drift.

create table public.waitlist_signups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  email text not null unique check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  whatsapp text not null check (char_length(whatsapp) between 4 and 25),
  ref_code text not null unique check (ref_code ~ '^[A-Z0-9]{4,12}$'),
  referred_by text references public.waitlist_signups (ref_code),
  queue_position bigint generated by default as identity (start with 248) unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint no_self_referral check (referred_by is null or referred_by <> ref_code)
);

create index waitlist_signups_referred_by_idx on public.waitlist_signups (referred_by);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger waitlist_signups_updated_at
  before update on public.waitlist_signups
  for each row execute function public.set_updated_at();

-- Deny-all RLS: no policies. Only the service role (server-side API routes) touches this table.
alter table public.waitlist_signups enable row level security;
